<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Inventory extends Model
{
    // Custom table name is 'inventories' as generated by Laravel
    protected $table = 'inventories';

    protected $fillable = [
        'product_id',
        'quantity',
        'reserved_quantity',
    ];

    /**
     * Get the product that owns this inventory record.
     */
    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    /**
     * Get the available quantity (total quantity minus reserved quantity).
     */
    public function availableQuantity(): int
    {
        return max(0, $this->quantity - $this->reserved_quantity);
    }
}
